# This file is used to configure the Process-PSModule workflow.
# Reference:
# - https://github.com/PSModule/Process-PSModule?tab=readme-ov-file#configuration

Test:
  CodeCoverage:
    PercentTarget: 80
#   TestResults:
#     Skip: true
#   SourceCode:
#     Skip: true
#   PSModule:
#     Skip: true
#   Module:
#     Windows:
#       Skip: true
#     MacOS:
#       Skip: true
# Build:
#   Docs:
#     Skip: true
Linter:
  env:
    VALIDATE_BIOME_FORMAT: false
    VALIDATE_BIOME_LINT: false
    VALIDATE_GITHUB_ACTIONS_ZIZMOR: false
    VALIDATE_JSCPD: false
    VALIDATE_JSON_PRETTIER: false
    VALIDATE_MARKDOWN_PRETTIER: false
    VALIDATE_YAML_PRETTIER: false
